create schema if not exists _performance_wrike;

revoke all on schema _performance_wrike from public, anon, authenticated;
grant usage on schema _performance_wrike to service_role;

create table if not exists _performance_wrike.squads (
  id bigint generated by default as identity primary key,
  id_wrike text not null unique,
  nome text not null,
  tipo_grupo text not null check (tipo_grupo in ('squad', 'area')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists _performance_wrike.pessoas (
  id bigint generated by default as identity primary key,
  id_wrike text not null unique,
  nome text not null,
  email text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists _performance_wrike.itens_trabalho (
  id bigint generated by default as identity primary key,
  id_wrike text not null unique,
  titulo text not null,
  link_wrike text,
  id_squad bigint references _performance_wrike.squads(id) on delete set null,
  nome_status text not null,
  grupo_status text not null,
  id_status_wrike text,
  itens jsonb not null default '[]'::jsonb,
  okr text,
  criado_no_wrike_em timestamptz,
  inicio_planejado_em timestamptz,
  prazo_em timestamptz,
  concluido_em timestamptz,
  atualizado_no_wrike_em timestamptz,
  descricao_preenchida boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists _performance_wrike.responsaveis_itens (
  id_item_trabalho bigint not null references _performance_wrike.itens_trabalho(id) on delete cascade,
  id_pessoa bigint not null references _performance_wrike.pessoas(id) on delete cascade,
  associado_em timestamptz not null default now(),
  ativo boolean not null default true,
  primary key (id_item_trabalho, id_pessoa)
);

create table if not exists _performance_wrike.mapeamentos_status (
  id_status_wrike text primary key,
  nome_status text not null,
  etapa_analitica text not null check (etapa_analitica in ('planejamento', 'execucao', 'concluido', 'nao_classificado')),
  considera_execucao boolean not null default false,
  encerra_ciclo boolean not null default false,
  ativo boolean not null default true,
  atualizado_em timestamptz not null default now()
);

create table if not exists _performance_wrike.historico_status_itens (
  id bigint generated by default as identity primary key,
  id_item_trabalho bigint not null references _performance_wrike.itens_trabalho(id) on delete cascade,
  id_status_anterior text,
  nome_status_anterior text,
  id_status_novo text,
  nome_status_novo text,
  ocorrido_em timestamptz not null,
  recebido_em timestamptz not null default now(),
  origem text not null check (origem in ('webhook', 'reconciliacao'))
);

create table if not exists _performance_wrike.eventos_wrike (
  id bigint generated by default as identity primary key,
  chave_idempotencia text not null unique,
  tipo_evento text not null,
  corpo jsonb not null,
  recebido_em timestamptz not null default now(),
  processado_em timestamptz,
  erro_processamento text
);

create table if not exists _performance_wrike.sincronizacoes_wrike (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('inicial', 'reconciliacao', 'webhook')),
  iniciado_em timestamptz not null default now(),
  finalizado_em timestamptz,
  itens_lidos integer not null default 0,
  itens_atualizados integer not null default 0,
  resultado text not null default 'em_andamento' check (resultado in ('em_andamento', 'sucesso', 'erro')),
  detalhe_erro text
);

create index if not exists itens_trabalho_squad_status_idx on _performance_wrike.itens_trabalho (id_squad, grupo_status);
create index if not exists itens_trabalho_concluido_idx on _performance_wrike.itens_trabalho (concluido_em desc) where concluido_em is not null;
create index if not exists itens_trabalho_ativos_idx on _performance_wrike.itens_trabalho (id_squad, atualizado_no_wrike_em desc) where grupo_status in ('Active', 'Deferred');
create index if not exists responsaveis_itens_pessoa_idx on _performance_wrike.responsaveis_itens (id_pessoa, id_item_trabalho) where ativo;
create index if not exists historico_status_item_ocorrido_idx on _performance_wrike.historico_status_itens (id_item_trabalho, ocorrido_em);
create index if not exists historico_status_ocorrido_idx on _performance_wrike.historico_status_itens (ocorrido_em desc);
create index if not exists eventos_wrike_recebido_idx on _performance_wrike.eventos_wrike (recebido_em desc);

create or replace function _performance_wrike.definir_atualizado_em()
returns trigger
language plpgsql
set search_path = _performance_wrike, pg_temp
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists squads_atualizado_em on _performance_wrike.squads;
create trigger squads_atualizado_em before update on _performance_wrike.squads for each row execute function _performance_wrike.definir_atualizado_em();
drop trigger if exists pessoas_atualizado_em on _performance_wrike.pessoas;
create trigger pessoas_atualizado_em before update on _performance_wrike.pessoas for each row execute function _performance_wrike.definir_atualizado_em();
drop trigger if exists itens_trabalho_atualizado_em on _performance_wrike.itens_trabalho;
create trigger itens_trabalho_atualizado_em before update on _performance_wrike.itens_trabalho for each row execute function _performance_wrike.definir_atualizado_em();

alter table _performance_wrike.squads enable row level security;
alter table _performance_wrike.pessoas enable row level security;
alter table _performance_wrike.itens_trabalho enable row level security;
alter table _performance_wrike.responsaveis_itens enable row level security;
alter table _performance_wrike.mapeamentos_status enable row level security;
alter table _performance_wrike.historico_status_itens enable row level security;
alter table _performance_wrike.eventos_wrike enable row level security;
alter table _performance_wrike.sincronizacoes_wrike enable row level security;

revoke all on all tables in schema _performance_wrike from public, anon, authenticated;
revoke all on all sequences in schema _performance_wrike from public, anon, authenticated;
grant select, insert, update, delete on all tables in schema _performance_wrike to service_role;
grant usage, select on all sequences in schema _performance_wrike to service_role;

create or replace function _performance_wrike.consultar_performance(
  p_inicio date,
  p_fim date,
  p_id_squad bigint default null,
  p_id_pessoa bigint default null
)
returns jsonb
language sql
stable
security invoker
set search_path = _performance_wrike, pg_temp
as $$
with itens_filtrados as (
  select i.*
  from itens_trabalho i
  where (p_id_squad is null or i.id_squad = p_id_squad)
    and (p_id_pessoa is null or exists (
      select 1 from responsaveis_itens ri
      where ri.id_item_trabalho = i.id and ri.id_pessoa = p_id_pessoa and ri.ativo
    ))
), ciclos as (
  select h.id_item_trabalho,
    min(h.ocorrido_em) filter (where m.considera_execucao and h.origem = 'webhook') as inicio_execucao,
    min(h.ocorrido_em) filter (where m.encerra_ciclo and h.origem = 'webhook') as fim_execucao
  from historico_status_itens h
  left join mapeamentos_status m on m.id_status_wrike = h.id_status_novo
  group by h.id_item_trabalho
), itens_com_ciclo as (
  select i.*, extract(epoch from (c.fim_execucao - c.inicio_execucao)) / 86400.0 as dias_ciclo
  from itens_filtrados i
  left join ciclos c on c.id_item_trabalho = i.id and c.fim_execucao >= c.inicio_execucao
), auditoria as (
  select i.id, i.id_wrike, i.titulo, i.link_wrike,
    coalesce(string_agg(p.problema, '; ' order by p.problema), '') as problemas
  from itens_filtrados i
  cross join lateral (values
    (case when not i.descricao_preenchida then 'Sem descrição' end),
    (case when i.prazo_em is null then 'Sem prazo' end),
    (case when i.okr is null or btrim(i.okr) = '' or lower(i.okr) = 'nenhum' then 'OKR ausente ou Nenhum' end),
    (case when jsonb_array_length(i.itens) = 0 then 'Itens ausente' end),
    (case when i.itens ? 'Outro' then 'Itens contém Outro' end),
    (case when not exists (select 1 from responsaveis_itens ri where ri.id_item_trabalho = i.id and ri.ativo) then 'Sem responsável' end)
  ) p(problema)
  where p.problema is not null
  group by i.id, i.id_wrike, i.titulo, i.link_wrike
), intervalos_status as (
  select h.id_item_trabalho,
    coalesce(m.nome_status, h.nome_status_novo, 'Não classificado') as etapa,
    extract(epoch from (lead(h.ocorrido_em) over (partition by h.id_item_trabalho order by h.ocorrido_em) - h.ocorrido_em)) / 86400.0 as dias
  from historico_status_itens h
  join itens_filtrados i on i.id = h.id_item_trabalho
  left join mapeamentos_status m on m.id_status_wrike = h.id_status_novo
), gargalos as (
  select etapa, round(avg(dias)::numeric, 1) as dias_medios
  from intervalos_status
  where dias is not null and dias >= 0
  group by etapa
), metricas as (
  select count(*) as total,
    count(*) filter (where grupo_status in ('Active', 'Deferred')) as em_andamento,
    count(*) filter (where concluido_em::date between p_inicio and p_fim) as entregues,
    count(*) filter (where grupo_status = 'Cancelled' and atualizado_no_wrike_em::date between p_inicio and p_fim) as cancelados,
    count(*) filter (where okr is not null and btrim(okr) <> '' and lower(okr) <> 'nenhum') as com_okr,
    (select count(*) from auditoria) as itens_com_problema
  from itens_filtrados
)
select jsonb_build_object(
  'periodo', jsonb_build_object('inicio', p_inicio, 'fim', p_fim),
  'metricas', (select to_jsonb(metricas) from metricas),
  'status', coalesce((select jsonb_agg(jsonb_build_object('nome', nome_status, 'quantidade', quantidade) order by quantidade desc)
    from (select nome_status, count(*) as quantidade from itens_filtrados group by nome_status) x), '[]'::jsonb),
  'squads', coalesce((select jsonb_agg(jsonb_build_object('id', s.id, 'nome', s.nome, 'tipo_grupo', s.tipo_grupo, 'em_andamento', coalesce(x.em_andamento, 0), 'entregues', coalesce(x.entregues, 0), 'cobertura_okr', coalesce(x.cobertura_okr, 0)) order by s.tipo_grupo, s.nome)
    from squads s left join (
      select id_squad, count(*) filter (where grupo_status in ('Active', 'Deferred')) as em_andamento,
        count(*) filter (where concluido_em::date between p_inicio and p_fim) as entregues,
        round(100.0 * count(*) filter (where okr is not null and btrim(okr) <> '' and lower(okr) <> 'nenhum') / nullif(count(*), 0), 1) as cobertura_okr
      from itens_filtrados group by id_squad
    ) x on x.id_squad = s.id where s.ativo), '[]'::jsonb),
  'pessoas', coalesce((select jsonb_agg(jsonb_build_object('id', p.id, 'nome', p.nome, 'em_andamento', coalesce(x.em_andamento, 0), 'entregues', coalesce(x.entregues, 0), 'dias_ciclo_medio', x.dias_ciclo_medio) order by coalesce(x.em_andamento, 0) desc, p.nome)
    from pessoas p left join (
      select ri.id_pessoa, count(*) filter (where i.grupo_status in ('Active', 'Deferred')) as em_andamento,
        count(*) filter (where i.concluido_em::date between p_inicio and p_fim) as entregues,
        round(avg(ic.dias_ciclo)::numeric, 1) as dias_ciclo_medio
      from responsaveis_itens ri join itens_filtrados i on i.id = ri.id_item_trabalho
      left join itens_com_ciclo ic on ic.id = i.id where ri.ativo group by ri.id_pessoa
    ) x on x.id_pessoa = p.id where p.ativo), '[]'::jsonb),
  'top_itens', coalesce((select jsonb_agg(jsonb_build_object('titulo', titulo, 'link_wrike', link_wrike, 'nome_status', nome_status, 'dias_ciclo', dias_ciclo, 'squad', squad) order by dias_ciclo desc)
    from (select ic.titulo, ic.link_wrike, ic.nome_status, round(ic.dias_ciclo::numeric, 1) as dias_ciclo, s.nome as squad from itens_com_ciclo ic left join squads s on s.id = ic.id_squad where ic.dias_ciclo is not null order by ic.dias_ciclo desc limit 10) t), '[]'::jsonb),
  'gargalos', coalesce((select jsonb_agg(jsonb_build_object('etapa', etapa, 'dias_medios', dias_medios) order by dias_medios desc) from gargalos), '[]'::jsonb),
  'auditoria', coalesce((select jsonb_agg(jsonb_build_object('id_wrike', id_wrike, 'titulo', titulo, 'link_wrike', link_wrike, 'problemas', problemas) order by titulo) from (select * from auditoria order by titulo limit 50) a), '[]'::jsonb),
  'avisos', jsonb_build_array('Bugs críticos e validação de hipóteses dependem de campos de classificação ainda não cadastrados.', 'Cycle time considera apenas transições registradas após a ativação do webhook.')
);
$$;

grant execute on function _performance_wrike.consultar_performance(date, date, bigint, bigint) to service_role;

-- Ponte mínima para a Edge Function. A função fica no schema exposto da Data API apenas porque
-- ele é exposto pelo PostgREST; não há concessão para visitantes nem usuários.
create or replace function api.consultar_performance_wrike(
  p_inicio date,
  p_fim date,
  p_id_squad bigint default null,
  p_id_pessoa bigint default null
)
returns jsonb
language sql
stable
security definer
set search_path = _performance_wrike, pg_temp
as $$
  select _performance_wrike.consultar_performance(p_inicio, p_fim, p_id_squad, p_id_pessoa);
$$;

grant usage on schema api to service_role;
revoke all on function api.consultar_performance_wrike(date, date, bigint, bigint) from public, anon, authenticated;
grant execute on function api.consultar_performance_wrike(date, date, bigint, bigint) to service_role;
